name: Update Note Repository with mdbook

on:
  push:
    branches:
      - master

jobs:
  update-note:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the mdbook repository
    - name: Checkout mdbook repository
      uses: actions/checkout@v3

    # Step 2: Download and install mdBook v0.4.52
    - name: Download and install mdBook v0.4.52
      run: |
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.52/mdbook-v0.4.52-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C $HOME/.cargo/bin
        export PATH=$PATH:$HOME/.cargo/bin

    # Step 3: Install jq and toml2json
    - name: Install jq and toml2json
      run: sudo apt-get install -y jq toml2json

    # Step 4: Get book title from book.toml and set it as output
    - name: Get book title from book.toml
      id: get_book_name
      run: |
        BOOK_NAME=$(jq -r '.book.title' <(toml2json ./book.toml))
        echo "Book title is: $BOOK_NAME"
        echo "::set-output name=BOOK_NAME::$BOOK_NAME"

    # Step 5: Build mdbook
    - name: Build mdbook
      run: mdbook build

    # Step 6: Checkout the note repository
    - name: Checkout note repository
      uses: actions/checkout@v3
      with:
        repository: DingWH03/note
        token: ${{ secrets.GITHUB_TOKEN }}
        path: note-repo

    # Step 7: Copy the book directory to the note repository and rename it
    - name: Copy book to note repository
      run: |
        # 获取从前一步中传递的 BOOK_NAME 输出
        BOOK_NAME=${{ steps.get_book_name.outputs.BOOK_NAME }}

        # 将 book 目录复制到 note 仓库并重命名
        cp -r ./book ./note-repo/book/${BOOK_NAME}

        # 将 book.toml 文件复制到 note 仓库的 list 目录并重命名
        cp ./book.toml ./note-repo/list/${BOOK_NAME}.toml

    # Step 8: Commit and push changes to note repository
    - name: Commit and push changes
      run: |
        BOOK_NAME=${{ steps.get_book_name.outputs.BOOK_NAME }}
        cd note-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update book directory and book.toml from mdbook build for ${BOOK_NAME}"
        git push origin master
